### PR TITLE
Clean up pandagma-* with shellcheck, and update config and get_data files

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
The only substantive change to the pandagma-* files was to remove suffix "_TEfilt" from ${DATA_DIR}.
Other changes in those files were to satisfy shellcheck.

Changes in the config and get_data files were in preparation for new pangene runs for all genera for legumeinfo.

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
Sorry - the PR was premature. The handling of the DATA_DIR in TEfilter still needs some work. I'll move this to draft and work on fixing that.

**Comment by StevenCannon-USDA** [comment]
OK - I think it's ready for review now.
I ended up making a lot of changes - but left this in place, after experimenting with some other options: `DATA_DIR_TEF="${DATA_DIR}_TEFilter"`

The thing is: it makes sense to have something like a `data_orig` directory and a `data_filtered` directory. These could be taken in as parameters, but I am not sure it is worth the potential extra confusion and mental load for the user. Also, a simple `data` default is nice if the optional TEfilter workflow isn't run.

As it stands now, a decent way to run the 'TEfilter' followed by the `pan` workflow (for example) is:
```
  pandagma TEfilter -c $CONFIG -s TEfilter
  pandagma pan -c $CONFIG -d data_TEFilter
```
... where `-d data_TEFilter` sets the data directory to that value.

The other significant changes were to `fetch-datastore.sh`, to retrieve `legume.TE_lib_2024.rpt.YFQ7.fna.gz` from the Data Store. I think this is working, but it is lightly tested.

I plan to go ahead and calculate pangenes for all of the main genera now - and then do a production run of the families. That should exercise the code pretty well.

**Review by nathanweeks — CHANGES_REQUESTED** [review]
legume.TE_lib_2024.rpt.YFQ7.fna.gz is listed in all the config/*.conf files:

```
$ grep legume.TE_lib_2024.rpt.YFQ7.fna.gz config/*
config/Arachis3_5_2_0.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Cicer3_4_2_0.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Glycine5_21_29_6.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Glycine_7_3_2.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Medicago3_8_0_16.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Phaseolus3_7_1_0.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Vigna4_7_1_4.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/Zea_7_2_0.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family3_18_3.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family3_4_3.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family3_sup.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family3_sup_ur.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family3_ur.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family_7_3.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
config/family_ur.conf:  legume.TE_lib_2024.rpt.YFQ7.fna.gz
```

Though it's only listed in a couple of the get_data/*.mk files:

```
$ grep legume.TE_lib_2024.rpt.YFQ7.fna.gz get_data/*mk
get_data/Glycine_7_3_2.mk:legume.TE_lib_2024.rpt.YFQ7.fna.gz
get_data/Phaseolus3_7_1_0.mk:legume.TE_lib_2024.rpt.YFQ7.fna.gz
```

**Comment by StevenCannon-USDA** [comment]
Good catch. I've added that TE_lib file to the other .mk files now.

> Down the road, it seems the TEfilter functionality could eventually be absorbed into the relevant ingest step, and not require an extra manual step for the end-user to utilize?

Yes, I think that's a good idea. In fact, I had started to implement it that way, but got bogged down in thinking how to handle alternate starting points for the main workflows. After that initial exploration, it seemed easier to do the first-pass implementation as a separate pre-processing workflow. I don't mind revisiting the code once time is a little more abundant (if that ever happens).

**Review by nathanweeks — CHANGES_REQUESTED** [review]
A couple additional suggested changes to the pandagma TEfilter usage:

1. The listed `-m` option isn't implemented:

```
$ pandagma TEfilter -m
/workspaces/pandagma/bin/pandagma-common.sh: line 129: MORE_INFO: unbound variable
```

2. It would be helpful to mention where the output will be written; e.g.:

```
Output files are written to ./data_TEfilter (or -d <data_dir>_TEfilter, if the -d option is specified).
```

**Comment by StevenCannon-USDA** [comment]
Thanks. Corrections made.

**Review by nathanweeks — APPROVED** [review]

**Pull request merged**
